version: "3"
services:
  app:
    container_name: app
    restart: on-failure
    environment:
      PG_USERNAME: postgres
      PG_PASSWORD: postgres
      PG_DATABASE: bank_api_dev
      PG_PORT: 5432
      PG_HOSTNAME: database_dev
    build: .
    command: sh -c "./run.sh"
    ports:
      - "4000:4000"
    working_dir: /app
    depends_on:
      - database_dev
    networks:
      - backend
    volumes:
      - ./:/app

  database_dev:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bank_api_dev
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /.:/app
      - pgdata_dev:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pgdata_dev:

networks:
  backend:
    driver: bridge
