version: "3"
services:
  app:
    container_name: app
    restart: on-failure
    environment:
      PG_USERNAME: postgres
      PG_PASSWORD: 951753
      PG_DATABASE: bank_api_test
      PG_PORT: 5432
      PG_HOSTNAME: database_test
    build: .
    command: sh -c "./run-test.sh"
    ports:
      - "4000:4000"
    working_dir: /app
    depends_on:
      - database_test
    networks:
      - backend
    volumes:
      - ./:/app

  database_test:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 951753
      POSTGRES_DB: bank_api_test
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /.:/app
      - pgdata_test:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pgdata_test:

networks:
  backend:
    driver: bridge
