name: CI
 
on: [push, pull_request]
 
env:
  MIX_ENV: test
 
jobs:
  build-and-test:
    name: Build and Tests
    runs-on: ${{ matrix.os }}
 
    strategy:
      matrix:
        os: [ubuntu-20.04]
        elixir: [1.11.2]
        otp: [23.3.4]
 
    services:
      postgres:
        image: postgres:12.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: kiz_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
 
    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2
 
    - name: Setup Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}
        experimental-otp: true
 
    - name: Restore Dependencies, Build & Dialyzer PLTs Cache
      uses: actions/cache@v2
      with:
        path: | 
          deps
          _build
          priv/plts
        key: ${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}
 
    - name: Install Dependencies
      run: mix deps.get
 
    - name: Setup DB
      run: mix ecto.setup
 
    - name: Run Tests
      run: mix test
 
    - name: Check Formatting
      run: mix format --check-formatted
 
    - name: Review Code With Credo
      run: mix credo
 
    - name: Typecheck With Dialyzer
      run: mix dialyzer

  deploy:
    needs: test # Will only run if the test job succeeds
    if: github.ref == 'refs/heads/master' # Only run this job if it is on the master branch

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master # Checkout out master instead of the latest commit
          fetch-depth: 0 # Checkout the whole branch

      - uses: mhanberg/gigalixir-action@v0.3.0
        with:
          GIGALIXIR_USERNAME: ${{ secrets.GIGALIXIR_USERNAME }}
          GIGALIXIR_PASSWORD: ${{ secrets.GIGALIXIR_PASSWORD }}
          GIGALIXIR_APP: bankapi 
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          MIGRATIONS: false # defaults to true
